project 'SampleApp_Swift.xcodeproj'

platform :ios, '10.0'

target 'SampleApp_Swift' do
  use_frameworks!

  # pod 'SKYLINK', '~> 2.2.1'
  # If facing issues with installation, please use:
  # pod 'SKYLINK', :git => 'https://github.com/Temasys/SKYLINK-iOS.git', :tag => '2.2.1'
  pod 'SKYLINK', :git => 'https://github.com/lakinduboteju/SKYLINK-iOS.git', :branch => 'iphone13-local-camera-video-fix'

end
